name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Publish win-x64 single file
        run: dotnet publish PostItExplorer/PostItExplorer.csproj -c Release -r win-x64 -p:PublishSingleFile=true --self-contained false

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: postit-explorer-win-x64
          path: PostItExplorer/bin/Release/net8.0-windows/win-x64/publish/*
